server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  application:
    name: sport-depth-chart-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 1qaz2wsx
  flyway:
    locations: classpath:/db/migration
springdoc:
  swagger-ui:
    path=/swagger-ui.html
